### ISSUE TITLE
Player Id is not incremented during connect

### ISSUE THREAD

**Issue by bmcgary** [bmcgary/TicketToRide#21]
When someone connects to the server socket the int id in MyWebSocketHandler.java is never incremented. When I try and hit the server (after logging in) to BuyATrainCard the server throws up saying the player ID is invalid (because it is still -1).

**Comment by rayn33** [comment]
Hmm, Strange how that got taken/left out.  I'll put the incrementer back in and push it.

**Comment by rayn33** [comment]
Oh its because it should be set and incremented by the serverfacade when you login/register.

Here is the code that does it in the MyWebSocketHandler:
personal_id = responseWrappers.get(0).getTargetIds().get(0);

So if it is still a -1, my guess would be that the serverfacade returned a -1(really unlikely) or you didn't login/register(also unlikely since you said you did it).

I'll be in the lab at 12 and we can see what is happening cause my code won't even login/register right now
